dependencies:
- name: aspringdemo2
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.8
- name: demo77
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: java2d
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: spring-app-demo
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
